#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \usepgfplotslibrary{groupplots}

#+LaTex_HEADER: \newcommand*{\shift}{\operatorname{q}}

#+title: Retroalimentación Actividad 2 - Sistema sensorial
#+author: Kjartan Halvorsen
#+date: 2021-02-25

* What do I want the students to understand?			   :noexport:

* Sistemas mecatrónicos

** Actividad 2

   Elaboración de especificaciones funcionales del *sistema sensorial* y selección de equipos
   
*** Propósito
    1. Identificar cuales serían *las variables físicas más relevantes para un mejor control* del proceso y en base a esto *definir las métricas funcionales* que debe cumplir el sistema sensorial.

    2. Seleccionar un conjunto de *equipos que cumpla con los requerimientos establecidos*, además de observar los aspectos económicos y de seguridad.

*** Notes                                                          :noexport:
    Esto era el propósito de la actividad 2. Dos partes. Primero: identificar que hay que medir, y que tan buenos tienen que ser nuestros sensores. Segundo: Buscar alternativas y evaluarlas. Selecciona los sensores.

    Solo un grupo entendió bien lo que se pidió.

    Retroalimentación general:
    1) Tratan de enfocar más. No tratan de incluir lo más cosas diferentes posible en su investigación y reporte. Mejor al reves: Tratan de quitar lo más cosas posible, para que lo que se queda es lo que de verdad es importante.
    2) Para un diseño o analisis sistematico: Hay que definir los requesitos (o criterios de diseño), y definirlos lo más especifico posible. Para el sistem sensorial: Cual variables tenemos que medir, y que tan exacto tenemos que saberlos.


   En calificar los reportes he tratado de ser bastante generoso. Porque la actividad pide algo avanzado, un trabajo para un ingeniero con experiencia. Tambien siento que no tomé tiempo de presentar bien la actividad, y claramente las instrucciones no eran suficiente detalladas, precisas ni claras.
   
** Análisis de un sistema mecatrónico

*** Requisitos / criterios de diseño

*** Identificar y describir elementos del sistem

    - mecanismo
    - actuadores
    - sensores
    - sistema de control

*** notes                                                          :noexport:
   En nuestra primera sesión platicamos sobre un Análisis de in sistema. 

    
** Requisitos / criterios de diseño

    #+begin_export latex
    \begin{center}
   \includegraphics[height=0.6\textheight]{../../figures/design-process-fig1.png}\\
   {\footnotesize  S.F. Love (1969) Modern design methods for electronics,  IEEE tr systems science and cybernetics}
   \end{center}
   #+end_export
   
*** notes                                                          :noexport:
    algo sobre los requisitos. como ingenieros nos gustan los problemos interesantes. y los problemas interesantes son los que tienen un multitud de soluciones posibles. donde tenemos que buscar la mejor solución, la solución optima. pero como definimos "que es mejor" o que es "optimal"? para eso necesitamos requesitos o criterios de diseño.

    Casi todos los grupos presentaron unos sensores comerciales en su reporte. Pero les faltaban el instrumento para evaluarlos. 

    esta gráfica es de una publicación algo viejo, aunque tiene el título modern design methods. es circular para enseñar que el proceso de diseño es iterativo. empieca con un análisis de las necesidades que resulta en un formulación del problema (función, rendimiento, delimitaciones, etc). basade en eso se define los criterios de diseño, que van a ser indispensables más allá en el proceso. ya viene la parte dónde buscamos diferentes soluciones alternativas. no solo una. se filtra las alternativas primero por factibilidad, usando los criterios. con las alternativas que se quedan, se busca optimar cada una (para que cumple lo mejor posible con los criterios), antes de seleccionar una solucion para implementar.
    muchas veces se necesia rediseño, y el circulo sique.

    esto para que entienden la importancia de tener un conjunto de requistos formulados en el trabajo de diseño. 
    

** Estudiantes contra expertos
   #+begin_center
   \includegraphics[width=0.5\linewidth]{../../figures/playground-design-student-experts.png}
   \includegraphics[width=0.3\linewidth]{../../figures/design-process-fig1.png}
   #+end_center
   #+begin_export latex
   \footnotesize Fig 3 de Atman et al. Engineering design processes: A comparison of students and expert practitioners. Journal of engineering education, 2007.
   #+end_export

*** notes                                                          :noexport:
    Y para dar aun más peso a la importancia de los criterios del diseño, les quiero comentar sobre este investigación de una publicación en la revista J Eng Ed. Es un experimento donde pidieron a un grupo de ingenieros con mucha experiencia y dos grupos de estudiantes resolver el misma problema. Y graban que tanto tiempo pusieron en diferentes parte del trabajo.

    Lo más interesante que vieron era que el grupo de ingenieros con experiencia asignaron bastante más tiempo en definier el problema (problem scoping). Que incluye definir los requisitos especificos que una solución buena tiene que satisfacer. Lo que tambien se llama criterios del diseño.
    
** Sistema mecatrónico del AC75

   #+begin_center
   \includegraphics[width=.76\textwidth]{../../figures/ac75-control-block-details}
   #+end_center

   - *Proceso* Aquí es un *sistema mecanico* o *mecanismo*
   - *Actuador* Conversión de una señal de información a fuerza/torque/flujo/energía
   - *Sensores*  Conversión de una variable física a una señal de información
   - *Controlador* Computadora o microcontrolador o PLC, recibe señales, ejecuta el algoritmo de control, manda acción de control (señales) a los actuadores.


*** notes                                                          :noexport:
    Voy a tratar de hacer más concreto lo que se pidió en la actividad, usando  nuestro ejemplo favorito. Y recordamos que en un sistema mecatrónico como esto se puede identificar estos subsistemas claves.
    
** Variables físicas

*** graphics
    :properties:
    :beamer_col: 0.5
    :end:

   \begin{center}
   \includegraphics[height=0.8\textheight]{../../figures/ac75-class-foil.png}
   \end{center}

   #+begin_export latex
   {\footnotesize from the ac75 class rule}
   #+end_export
*** text
    :properties:
    :beamer_col: 0.5
    :end:

   \begin{center}
   \includegraphics[width=0.8\textwidth]{../../figures/parameters-not-variables}
   \end{center}
     
*** notes                                                          :noexport:
    Como mencioné en mi retroalimentación de la actividad 1: Hay un montón de números en la definición completa del sistema, pero muchos de estos números son parámetros, que no cambian. En la cortina, su ancho por ejemplo puede ser diferente entre cortinas diferentes. Pero no va a cambiar en una cortina, y en instalación en particular no lo necesitamos medir.
    
** Variables físicas
*** graphics
    :properties:
    :beamer_col: 0.5
    :end:

   \begin{center}
   \includegraphics[height=0.8\textheight]{../../figures/ac75-class-foil.png}
   \end{center}

   #+begin_export latex
   {\footnotesize from the ac75 class rule}
   #+end_export
*** text
    :properties:
    :beamer_col: 0.5
    :end:

   - *Posición angular continua del brazo/ala*
   - Presión hydraulica
   - Estado de cargo de las pilas

*** notes                                                          :noexport:
    Identificamos algunas variables importantes en el sistema. Vamos a seguir con el análisis de la medición de posición.
    
** Posición del ala - Requisitos
*** graphics
    :properties:
    :beamer_col: 0.5
    :end:

   \begin{center}
   \includegraphics[height=0.6\textheight]{../../figures/ac75-class-foil.png}\\[-4mm]
   \includegraphics[height=0.3\textheight]{../../figures/ac75-rule-detail.png}
   \end{center}

*** text
    :properties:
    :beamer_col: 0.5
    :end:

**** Rango
    Gira de $0^\circ$ (posición más abajo) hasta $119^\circ$ (ala más arriba).

**** Resolución
    Asumiendo resolución deseada de $\epsilon_a = \unit{5}{\milli\meter}$ en la posición de la ala.

***** En posición angular del brazo
    \( \epsilon_b = \frac{\epsilon_a}{r} = \unit{\frac{5}{3500}}{\rad} = \unit{0.08}{\degree}\)
***** En posición lineal del pistón hidraulico
    \[ \epsilon_p = \unit{?}{\milli\meter}\]
    *Actividad individual*
*** Notes                                                          :noexport:
    Las instrucciones de la actividad solomente piden que buscan el rango y resolución adecuada para las varibles. Aqui es dado del 'Class Rule' que el movimiento del brazo tiene un rango de 119 grados. Fácil. Para la resolución tenemos que pensar un poquito mas. Con 'resolución' se entiende el cambio mínimo de la variable que se puede detectar. No encontré información sobre esto, entonces tuve que hacer una suposición.  Pensé que un movimiento de medio centimetro en la posición del ala sí tiene consequencia cuando está bajo del agua en movimiento. Para saber que significa esto en resolución del ángulo del brazo tenemos que usar la relación entre cambio en ángulo y cambio en un punto a cierta radie. Este nos da eps_b = eps_a/r. Como saben, el brazo se mueve con un cilindro hidraulico. Entonces es importante saber que resolución necesitamos en la posición del brazo. Nota el radie sería este : rh = sqrt(da^2 + db^2).
    Por favor piensan bien y responden en el chat: que sería la resolución requerida en la posición del pistón?

    La verdad es que depende de la posición del brazo. 
    
    
#+BEGIN_SRC python :session  :results output 
  import numpy as np  
  eps_a = 5e-3
  r = 3.5
  da = 0.246
  db = 0.377
  rp = np.sqrt(da**2 + db**2)
  eps_b = eps_a/r
  eps_p = eps_b*rp

  rang = 119*np.pi/180
  strokelength = 2*rp*np.cos(np.pi/2 - rang/2)

  print("Radius rp = %0.2f mm" %(rp*1000))
  print("Resolucion eps_b = %0.2f rad = %0.2f grados" %(eps_b, eps_b*180/np.pi))
  print("Resolucion eps_p = %0.2f mm" %(eps_b*rp*1000))
  print("Strokelength = %0.2f mm" %(strokelength*1000))


  #+END_SRC

#+RESULTS:
: Radius rp = 450.16 mm
: Resolucion eps_b = 0.00 rad = 0.08 grados
: Resolucion eps_p = 0.64 mm
: Strokelength = 775.74 mm

** Posición del ala - Alternativ comercial 1
    #+begin_export latex
    \begin{center}
    \includegraphics[width=0.4\linewidth]{../../figures/PosSensor.png}\\
    {\footnotesize Fuente: SIKO GmbH}
    \end{center}
    #+end_export

    | Modelo     | Rango [mm] | Resolución DA | Resolución [mm] |
    |------------+------------+--------+----------|
    | SGH10-500  |        500 | 12 bit |     0.12 |
    | SGH10-1000 |       1000 | 12 bit |     0.24 |


*** Notes                                                          :noexport:

#+BEGIN_SRC python :session  :results output 
  import numpy as np  
  rang = 1000.0 #mm
  res = rang/(2**12)
  print("Resolucion = %0.2f mm" %(res))


  #+END_SRC

#+RESULTS:
: Resolucion = 0.24 mm



** Posición del ala - Alternativ comercial 2

*** Encoder absoluto
   #+begin_export latex
   \begin{center}
   \includegraphics[width=0.35\textwidth]{../../figures/encoder-disc-absolute}\\
   Encoder de cuatro bits.
   \end{center}
   #+end_export

   
   *Actividad individual* Cual es la resolución (en grados) de un encoder absoluto de cuatro bits? Y de ocho bits?



** Posición del ala - Alternativ comercial 2

*** Encoder absoluto
   #+begin_export latex
   \begin{center}
   \includegraphics[width=0.35\textwidth]{../../figures/encoder-disc-absolute}\\
   Encoder de cuatro bits.
   \end{center}
   #+end_export

   Resolución requerida para el angula del brazo: \(\epsilon_b = 0.08^\circ\)

   
   *Actividad en pares* Cual sería el número de bits necesario para un encoder absoluto montado directamente en el eje del brazo?


*** Notes                                                          :noexport:

  #+BEGIN_SRC python :session  :results output 
    import numpy as np  
    eps_b = 0.08 #grados
    #360/2^x = 0.08
    # 2^x = 360/0.08
    # x = log2(360/0.08)
    res = np.log2(360/eps_b)
    print("Resolucion in bits = %0.2f " %(res))


  #+END_SRC

#+RESULTS:
: Resolucion in bits = 12.14

** Posición del ala - Alternativ comercial 2
    #+begin_export latex
    \begin{center}
    \includegraphics[width=0.99\linewidth]{../../figures/dynapar-absolute-encoder.png}\\
    {\footnotesize Fuente: Dynapar.com}
    \end{center}
    #+end_export


** Cual eligir?

   Las dos alternativas cumplen con los requesitos...

   
* Hidraulica                                                       :noexport:
** Sobre el actuador hidraulico

   Acumulador de alta presión cilindo, 1.5m altura, 0.1m radius
   250 bar.
   
   Asumiendo que la 
   
** Sobre el actuador hidraulico


